name: Deploy Node.js App

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy-production:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Copy .env-example to .env
      run: cp .env-example .env

    - name: Install dependencies
      run: npm install

    - name: Deploy to FTP (Production)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.PROD_FTP_HOST }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        timeout: 190000
